import Head from 'next/head';
import Link from 'next/link';
import { FormEventHandler, useState } from 'react';

import { FaRegUserCircle as UserIcon } from 'react-icons/fa';
import { GrFormNextLink as LinkIcon } from 'react-icons/gr';
import { MdAlternateEmail as EmailIcon, MdDone as DoneIcon } from 'react-icons/md';
import { BiLock as IconLock, BiLockOpen as IconLockOpen, BiUser as userIconInput } from 'react-icons/bi';

import Container from '@/components/Container';
import Input from '@/components/Input';
import Button from '@/components/Button';
import Logo from '@/components/Logo';

import styles from '@/styles/Home.module.css';


const Home = () => {
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const submitSiginForm: FormEventHandler = e => {
    e && e.preventDefault();
  };

  const submitCreateRoom: FormEventHandler = e => {
    e && e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Watching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Logo />

        <div className={styles.container__login__createRoom}>
          <div className={styles.container__login}>
            <UserIcon className={styles.userIcon} />

            <div className={[styles.title, styles.item].join(' ')}>
              <span className={styles.line} />
              <span className={styles.text}>SIGN IN</span>
              <span className={styles.line} />
            </div>

            <Link href="/user/sigup" className={styles.link}>
              Create account <LinkIcon className={styles.link_icon} />
            </Link>
            <form className={styles.form} onSubmit={submitSiginForm}>
              <Input Icon={EmailIcon} type="email" placeHolder="Email" value={email} setValue={setEmail} />
              <Input className={styles.item} type={showPassword ? 'text' : 'password'} placeHolder="Password" value={password} setValue={setPassword}>
                {showPassword ?
                  <Button title="Hidden password" type="button" onClick={() => setShowPassword(false)}><IconLockOpen /></Button> :
                  <Button title="Show password" type="button" onClick={() => setShowPassword(true)}><IconLock /></Button>
                }
              </Input>
              <Button className={[styles.item, styles.btn].join(' ')} type="submit" onClick={() => submitSiginForm}>
                Sign In
              </Button>
            </form>
          </div>

          <div className={styles.container__createRoom}>
            <div className={styles.createRoom}>
              <h1 className={styles.title}>Create a room without account</h1>
              <form className={styles.form} onSubmit={submitCreateRoom}>
                <Input className={styles.item} Icon={userIconInput} type="text" placeHolder="Username" value={username} setValue={setUsername} />
                <Button className={[styles.item, styles.btn].join(' ')} type="submit" onClick={() => submitCreateRoom}>
                  Create Room
                </Button>
              </form>
            </div>
            <ul className={styles.list}>
              <li className={styles.listItem}>
                <DoneIcon className={styles.doneIcon} color='#4ECB71' />
                Watch youtube with your friends
              </li>

              <li className={styles.listItem}>
                <DoneIcon className={styles.doneIcon} color='#4ECB71' />
                Watch twitch with your friends
              </li>

              <li className={styles.listItem}>
                <DoneIcon className={styles.doneIcon} color='#4ECB71' />
                Talk to your friends in the integrated chat room
              </li>

              <li className={styles.listItem}>
                <DoneIcon className={styles.doneIcon} color='#4ECB71' />
                Create and organize contents into playlists
              </li>

              <li className={styles.listItem}>
                <DoneIcon className={styles.doneIcon} color='#4ECB71' />
                Synchronized player for video
              </li>
            </ul>
          </div>
        </div>

      </Container>
    </>);
};

export default Home;
